export { default as Logo} from './Img/logo.png';
export { default as BannerImg } from './Img/banner.png'; 
export {default as Assisted } from './Img/assisted-icon.png';
export {default as Rest } from './Img/rest-icon.png';
export {default as Nursing } from './Img/nursing-icon.png';
export {default as HomeHappiest } from './Img/home-happiest.jpg';
export {default as BackgroundBanner} from './Img/backround-im.jpg';
export {default as Experience} from './Img/background_achieve.png';
export {default as ServiceBackground} from './Img/service_background.png';
export {default as Experience1} from './Img/Group 24.png';
export {default as Experience2} from './Img/Group 97.png';
export {default as Experience3} from './Img/Group 98.png';
export {default as Experience4} from './Img/Group 99.png';
export {default as Map} from './Img/map.png';
export {default as Appointment} from './Img/appointment.png';
export {default as AboutBanner} from './Img/about_banner.jpg';
export {default as Service1} from './Img/service_1.jpg';
export {default as Service2} from './Img/service_2.jpg';
export {default as Service3} from './Img/service_3.jpg';
export {default as ChooseImg} from './Img/choose_img.png';
export {default as OurCareBack} from './Img/our_care.png';
export {default as OurCare1} from './Img/cardio_care.jpg';
export {default as OurCare2} from './Img/pulmory_care.jpg';
export {default as OurCare3} from './Img/rehab_therapie.jpg';
export {default as Vegetable} from './Img/vegatables.jpg';